#!/usr/bin/env python3
"""
gen_tool_catalog.py — Auto-generate docs/TOOL_CATALOG.md from ToolRegistry.

Usage:
    python3 scripts/gen_tool_catalog.py

Output:
    docs/TOOL_CATALOG.md
"""

import sys
import os
from pathlib import Path
from collections import defaultdict

# Ensure project root is on path
sys.path.insert(0, str(Path(__file__).parent.parent))

from bughound.core.tool_registry import get_all_tools

STAGE_ORDER = ["recon", "historical", "light_scan", "deep_scan", "validation", "reporting"]
RISK_ORDER  = ["safe", "medium", "intrusive"]

def default_enabled(risk: str) -> str:
    return "yes" if risk != "intrusive" else "no"


def by_stage_table(tools) -> str:
    stage_tools = defaultdict(list)
    for t in tools:
        stage_tools[t.stage].append(t)

    lines = ["# BugHound Tool Catalog\n",
             "_Auto-generated by `scripts/gen_tool_catalog.py`. Do not edit by hand._\n"]

    lines.append("---\n")
    lines.append("## Grouped by Stage\n")

    for stage in STAGE_ORDER:
        bucket = stage_tools.get(stage, [])
        if not bucket:
            continue
        lines.append(f"### {stage}\n")
        lines.append("| Tool | Risk | Default Enabled |")
        lines.append("|------|------|-----------------|")
        for t in bucket:
            lines.append(f"| `{t.name}` | {t.risk} | {default_enabled(t.risk)} |")
        lines.append("")

    return "\n".join(lines)


def by_risk_section(tools) -> str:
    risk_tools = defaultdict(list)
    for t in tools:
        risk_tools[t.risk].append(t)

    lines = ["---\n", "## Grouped by Risk\n"]

    for risk in RISK_ORDER:
        bucket = risk_tools.get(risk, [])
        if not bucket:
            continue
        lines.append(f"### {risk}\n")
        lines.append("| Tool | Stage | Default Enabled |")
        lines.append("|------|-------|-----------------|")
        for t in bucket:
            lines.append(f"| `{t.name}` | {t.stage} | {default_enabled(t.risk)} |")
        lines.append("")

    return "\n".join(lines)


def main():
    tools = get_all_tools()

    out_path = Path(__file__).parent.parent / "docs" / "TOOL_CATALOG.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    content = by_stage_table(tools) + "\n" + by_risk_section(tools)
    out_path.write_text(content)

    print(f"✓ Written {len(tools)} tools → {out_path}")


if __name__ == "__main__":
    main()
